### ISSUE TITLE
QuerydslJdbcRepositoryFactory can't find a static field of the same type in class

### ISSUE THREAD

**Issue by mmdance** [infobip/infobip-spring-data-querydsl#10]
I have a problem:
```
Caused by: java.lang.IllegalArgumentException: Did not find a static field of the same type in class com.develop.jinamaven.jinamaven.qEntities.QCategoryTable at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactory.getRelationalPathBase(QuerydslJdbcRepositoryFactory.java:133) ~[infobip-spring-data-jdbc-querydsl-3.0.0.jar:na]
```
And I don't know how to solve it. The maven plugin generates QEntities but QuerydslJdbcRepositoryFactory can't find the static field but the field exists. 
![image](https://user-images.githubusercontent.com/44356971/100551490-8e0c2100-3289-11eb-943c-5f6a2ba2f78b.png)
QuerydslJdbcRepositoryFactory tries to perform 
```java
ReflectionUtils.findField(queryType, queryType.getSimpleName().substring(1));
```
![image](https://user-images.githubusercontent.com/44356971/100551503-a5e3a500-3289-11eb-9446-7a7f74e17dd0.png)
And obviously it returns null, because the field is categoryTable and it tries to find CategoryTable. The expression was successful
```java
ReflectionUtils.findField(queryType, Character.toLowerCase(queryType.getSimpleName().charAt(1)) + queryType.getSimpleName().substring(2)
```

![image](https://user-images.githubusercontent.com/44356971/100551519-c27fdd00-3289-11eb-91a8-572c8c9994ec.png)
Can someone help me?

**Comment by lpandzic** [comment]
Hello, can you please submit a code example that reproduces the issue?
Are you using infobip-spring-data-jdbc-annotation-processor?
As a starting point I suggest you checkout https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-jdbc-querydsl/src/test/java/com/infobip/spring/data/jdbc/QuerydslJdbcRepositoryTest.java

**Comment by mmdance** [comment]
My repository
`@Repository
public interface CategoryRepository extends QuerydslJdbcRepository<Category, QCategoryTable, Long> {
    boolean existsByTitle(String title);
}`
My jdbc configuration
`@Configuration
public class CustomJdbcConfiguration extends AbstractJdbcConfiguration {
    @Bean
    public DataSource getDataSource()
    {
        return DataSourceBuilder.create()
                .driverClassName("com.mysql.cj.jdbc.Driver")
                .url("jdbc:mysql://localhost:3306/jinadb?serverTimezone=UTC&useJvmCharsetConverters=true")
                .username("root")
                .password("0451")
                .build();
    }

    @Bean
    com.querydsl.sql.Configuration querydslConfiguration() {
        SQLTemplates templates = MySQLTemplates.builder().build();
        com.querydsl.sql.Configuration configuration = new com.querydsl.sql.Configuration(templates);
        configuration.setExceptionTranslator(new SpringExceptionTranslator());
        return configuration;
    }

    @Bean
    SQLQueryFactory sqlQueryFactory(DataSource dataSource) {
        return new SQLQueryFactory(querydslConfiguration(), new TransactionAwareDataSourceProxy(dataSource));
    }
}
`
@EnableQuerydslJdbcRepository
`@SpringBootApplication
@EnableQuerydslJdbcRepositories
public class JinaMavenApplication {

    public static void main(String[] args) {
        SpringApplication.run(JinaMavenApplication.class, args);
    }

}`
Ok if I shoud use infobip-spring-data-jdbc-annotation-processor how I can do that? Just insert it into the maven-compiler-plugin?

**Comment by lpandzic** [comment]
Just add it as a dependency. Both Maven and Intellij IDEA by default enable annotation processors.

**Comment by lpandzic** [comment]
Does the above code break on startup?

**Comment by mmdance** [comment]
The exception stack trace
```
Caused by: java.lang.IllegalArgumentException: Did not find a static field of the same type in class com.develop.jinamaven.jinamaven.qEntities.QCategoryTable
	at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactory.getRelationalPathBase(QuerydslJdbcRepositoryFactory.java:133) ~[infobip-spring-data-jdbc-querydsl-3.0.0.jar:na]
	at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactory.getRelationalPathBase(QuerydslJdbcRepositoryFactory.java:126) ~[infobip-spring-data-jdbc-querydsl-3.0.0.jar:na]
	at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactory.getTargetRepository(QuerydslJdbcRepositoryFactory.java:78) ~[infobip-spring-data-jdbc-querydsl-3.0.0.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:312) ~[spring-data-commons-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:297) ~[spring-data-commons-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:212) ~[spring-data-commons-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.data.util.Lazy.get(Lazy.java:94) ~[spring-data-commons-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:300) ~[spring-data-commons-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.data.jdbc.repository.support.JdbcRepositoryFactoryBean.afterPropertiesSet(JdbcRepositoryFactoryBean.java:184) ~[spring-data-jdbc-1.1.6.RELEASE.jar:1.1.6.RELEASE]
	at com.infobip.spring.data.jdbc.QuerydslJdbcRepositoryFactoryBean.afterPropertiesSet(QuerydslJdbcRepositoryFactoryBean.java:152) ~[infobip-spring-data-jdbc-querydsl-3.0.0.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	... 44 common frames omitted
```
the generated entity
'''java
/**
 * QCategoryTable is a Querydsl query type for QCategoryTable
 */
@Generated("com.querydsl.sql.codegen.MetaDataSerializer")
public class QCategoryTable extends com.querydsl.sql.RelationalPathBase<QCategoryTable> {

    private static final long serialVersionUID = 1966254115;

    public static final QCategoryTable categoryTable = new QCategoryTable("category_table");

    public final NumberPath<Long> id = createNumber("id", Long.class);

    public final StringPath title = createString("title");

    public final com.querydsl.sql.PrimaryKey<QCategoryTable> primary = createPrimaryKey(id);

    public final com.querydsl.sql.ForeignKey<QProduct> _productCategoryFk = createInvForeignKey(id, "category_id");

    public final com.querydsl.sql.ForeignKey<QCategoryCharacteristicValue> _valueCategoryFk = createInvForeignKey(id, "category_id");
// ...generated code
}
'''
application fails here
![image](https://user-images.githubusercontent.com/44356971/100553154-cd8c3a80-3294-11eb-87ff-f00b27540a69.png)

**Comment by mmdance** [comment]
> Just add it as a dependency. Both Maven and Intellij IDEA by default enable annotation processors.

I can't find maven dependencies. Should I download the jar file?

**Comment by lpandzic** [comment]
Unfortunately, it wasn't released yet - https://github.com/infobip/infobip-spring-data-querydsl/commits/master and for a reason, I don't believe it's ready for prime time yet as it hasn't been tried out outside tests. You can try building it locally (`mvn clean install`) and see if that helps.

Can you share full code that fails (I don't see source of CategoryTable)?

**Comment by mmdance** [comment]
Category
```java
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Table("category_table")
public class Category {
    @Id
    private Long id;
    private String title;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Category category = (Category) o;
        return id.equals(category.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
```

CategoryTable (Category) generated from database by querydsl maven plugin
```java
package com.develop.jinamaven.jinamaven.qEntities;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;

import com.querydsl.sql.ColumnMetadata;
import java.sql.Types;




/**
 * QCategoryTable is a Querydsl query type for QCategoryTable
 */
@Generated("com.querydsl.sql.codegen.MetaDataSerializer")
public class QCategoryTable extends com.querydsl.sql.RelationalPathBase<QCategoryTable> {

    private static final long serialVersionUID = 1966254115;

    public static final QCategoryTable categoryTable = new QCategoryTable("category_table");

    public final NumberPath<Long> id = createNumber("id", Long.class);

    public final StringPath title = createString("title");

    public final com.querydsl.sql.PrimaryKey<QCategoryTable> primary = createPrimaryKey(id);

    public final com.querydsl.sql.ForeignKey<QProduct> _productCategoryFk = createInvForeignKey(id, "category_id");

    public final com.querydsl.sql.ForeignKey<QCategoryCharacteristicValue> _valueCategoryFk = createInvForeignKey(id, "category_id");

    public QCategoryTable(String variable) {
        super(QCategoryTable.class, forVariable(variable), "null", "category_table");
        addMetadata();
    }

    public QCategoryTable(String variable, String schema, String table) {
        super(QCategoryTable.class, forVariable(variable), schema, table);
        addMetadata();
    }

    public QCategoryTable(String variable, String schema) {
        super(QCategoryTable.class, forVariable(variable), schema, "category_table");
        addMetadata();
    }

    public QCategoryTable(Path<? extends QCategoryTable> path) {
        super(path.getType(), path.getMetadata(), "null", "category_table");
        addMetadata();
    }

    public QCategoryTable(PathMetadata metadata) {
        super(QCategoryTable.class, metadata, "null", "category_table");
        addMetadata();
    }

    public void addMetadata() {
        addMetadata(id, ColumnMetadata.named("id").withIndex(1).ofType(Types.BIGINT).withSize(19).notNull());
        addMetadata(title, ColumnMetadata.named("title").withIndex(2).ofType(Types.VARCHAR).withSize(45).notNull());
    }

}
```
Querydsl maven plugin
```
<plugin>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-maven-plugin</artifactId>
                <version>${querydsl.version}</version>
                <executions>
                    <execution>
                        <id>generate-query-dsl-classes</id>
                        <goals>
                            <goal>export</goal>
                        </goals>
                        <configuration>
                            <jdbcDriver>com.mysql.cj.jdbc.Driver</jdbcDriver>
                            <jdbcUrl>jdbc:mysql://localhost:3306/jinadb?serverTimezone=UTC&amp;useJvmCharsetConverters=true</jdbcUrl>
                            <jdbcUser>quser</jdbcUser>
                            <jdbcPassword>1450</jdbcPassword>
                            <lowerCase>false</lowerCase>
                            <schemaPattern>jinadb%</schemaPattern>
                            <tableNamePattern>
                                %basket,
                                %basket_product,
                                %category_characteristic_value,
                                %category_table,
                                %characteristic,
                                %order,
                                %order_product,
                                product%,
                                %permission,
                                %user
                            </tableNamePattern>
                            <packageName>com.develop.jinamaven.jinamaven.qEntities</packageName>
                            <targetFolder>${project.basedir}/target/generated-sources/annotations</targetFolder>
                        </configuration>
                    </execution>
                    <execution>
                        <id>compile-query-dsl-classes</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceFolder>${project.basedir}/target/generated-sources/annotations</sourceFolder>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>8.0.22</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by mmdance** [comment]
category_table database definition
```sql
-- auto-generated definition
create table category_table
(
    id    bigint auto_increment
        primary key,
    title varchar(45) not null
);
```

**Comment by mmdance** [comment]
I add the infobip-spring-data-jdbc-annotation-processor but it still doesn't work.

**Comment by lpandzic** [comment]
What you most likely need is NamingStrategy such as https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-jdbc-querydsl/src/main/java/com/infobip/spring/data/jdbc/PascalCaseNamingStrategy.java.
I'll release 4.0.0 soon which should create it by default:
https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-jdbc-querydsl/src/main/java/com/infobip/spring/data/jdbc/QuerydslJdbcConfiguration.java
https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-jdbc-querydsl/src/main/java/com/infobip/spring/data/jdbc/EnableQuerydslJdbcRepositories.java#L13

**Comment by lpandzic** [comment]
I've released it, hopefully it'll be available shortly.

**Comment by mmdance** [comment]
Thank you for help but it still doesn't work
The code break on start up again
```java
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by FernFlower decompiler)
//

package com.infobip.spring.data.jdbc;

import com.querydsl.core.types.ConstructorExpression;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.Projections;
import com.querydsl.sql.RelationalPath;
import com.querydsl.sql.RelationalPathBase;
import com.querydsl.sql.SQLQueryFactory;
import java.lang.reflect.Field;
import java.util.Map;
import java.util.Objects;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.core.ResolvableType;
import org.springframework.data.jdbc.core.JdbcAggregateTemplate;
import org.springframework.data.jdbc.core.convert.DataAccessStrategy;
import org.springframework.data.jdbc.core.convert.JdbcConverter;
import org.springframework.data.jdbc.repository.support.JdbcRepositoryFactory;
import org.springframework.data.mapping.PreferredConstructor;
import org.springframework.data.mapping.PreferredConstructor.Parameter;
import org.springframework.data.mapping.callback.EntityCallbacks;
import org.springframework.data.mapping.model.PreferredConstructorDiscoverer;
import org.springframework.data.relational.core.mapping.RelationalMappingContext;
import org.springframework.data.repository.core.RepositoryInformation;
import org.springframework.data.repository.core.RepositoryMetadata;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcOperations;
import org.springframework.util.ReflectionUtils;

class QuerydslJdbcRepositoryFactory extends JdbcRepositoryFactory {
    private final RelationalMappingContext context;
    private final JdbcConverter converter;
    private final ApplicationEventPublisher publisher;
    private final DataAccessStrategy accessStrategy;
    private final SQLQueryFactory sqlQueryFactory;
    private EntityCallbacks entityCallbacks;

    public QuerydslJdbcRepositoryFactory(DataAccessStrategy dataAccessStrategy, RelationalMappingContext context, JdbcConverter converter, ApplicationEventPublisher publisher, NamedParameterJdbcOperations operations, SQLQueryFactory sqlQueryFactory) {
        super(dataAccessStrategy, context, converter, publisher, operations);
        this.publisher = publisher;
        this.context = context;
        this.converter = converter;
        this.accessStrategy = dataAccessStrategy;
        this.sqlQueryFactory = sqlQueryFactory;
    }

    public void setEntityCallbacks(EntityCallbacks entityCallbacks) {
        super.setEntityCallbacks(entityCallbacks);
        this.entityCallbacks = entityCallbacks;
    }

    protected Class<?> getRepositoryBaseClass(RepositoryMetadata repositoryMetadata) {
        return SimpleQuerydslJdbcRepository.class;
    }

    protected Object getTargetRepository(RepositoryInformation repositoryInformation) {
        JdbcAggregateTemplate template = new JdbcAggregateTemplate(this.publisher, this.context, this.converter, this.accessStrategy);
        Class<?> type = repositoryInformation.getDomainType();
        RelationalPath<?> relationalPathBase = this.getRelationalPathBase(repositoryInformation);
        ConstructorExpression<?> constructor = this.getConstructorExpression(type, relationalPathBase);
        SimpleQuerydslJdbcRepository<?, ?, ?> repository = new SimpleQuerydslJdbcRepository(template, this.context.getRequiredPersistentEntity(type), this.sqlQueryFactory, constructor, relationalPathBase);
        if (this.entityCallbacks != null) {
            template.setEntityCallbacks(this.entityCallbacks);
        }

        return repository;
    }

    private ConstructorExpression<?> getConstructorExpression(Class<?> type, RelationalPath<?> pathBase) {
        PreferredConstructor<?, ?> constructor = PreferredConstructorDiscoverer.discover(type);
        if (constructor == null) {
            throw new IllegalArgumentException("Could not discover preferred constructor for " + type);
        } else {
            Map<String, Path<?>> columnNameToColumn = (Map)pathBase.getColumns().stream().collect(Collectors.toMap((column) -> {
                return column.getMetadata().getName();
            }, Function.identity()));
            Stream var10000 = constructor.getParameters().stream().map(Parameter::getName);
            Objects.requireNonNull(columnNameToColumn);
            Path<?>[] paths = (Path[])var10000.map(columnNameToColumn::get).toArray((x$0) -> {
                return new Path[x$0];
            });
            return Projections.constructor(type, paths);
        }
    }

    private RelationalPathBase<?> getRelationalPathBase(RepositoryInformation repositoryInformation) {
        ResolvableType queryType = ResolvableType.forClass(repositoryInformation.getRepositoryInterface()).as(QuerydslJdbcRepository.class).getGeneric(new int[]{1});
        if (queryType.getRawClass() == null) {
            throw new IllegalArgumentException("Could not resolve query class for " + repositoryInformation);
        } else {
            return this.getRelationalPathBase(queryType.getRawClass());
        }
    }

    private RelationalPathBase<?> getRelationalPathBase(Class<?> queryType) {
        Field field = ReflectionUtils.findField(queryType, queryType.getSimpleName().substring(1));
        if (field == null) {
            throw new IllegalArgumentException("Did not find a static field of the same type in " + queryType);
        } else {
            return (RelationalPathBase)ReflectionUtils.getField(field, (Object)null);
        }
    }
}
```
I think I can solve the problem by specifying `<namingStrategyClass>` in maven compiler plugin configuration. But I think it's not normal way to solve the problem. 
The line of code returns null
```java
Field field = ReflectionUtils.findField(queryType, queryType.getSimpleName().substring(1));
```
It tries to find field with name "Category" (I renamed "category_table" to "category") again, but the field's name is "category"
```java
public static final QCategory category = new QCategory("category");
```

**Comment by lpandzic** [comment]
Try with `4.0.0` when it's out without maven plugin, `infobip-spring-data-jdbc-querydsl` depends on `infobip-spring-data-jdbc-annotation-processor` so no additional dependency should be required.
Execute `mvn clean compile` and then try again.

**Comment by lpandzic** [comment]
https://search.maven.org/search?q=g:com.infobip%20AND%20a:infobip-spring-data-jdbc-querydsl%20AND%20v:4.0.0

**Comment by mmdance** [comment]
I've added the  `infobip-spring-data-jdbc-querydsl:4.0.0` and `infobip-spring-data-jdbc-annotation-processor` to dependencies. Should I add some annotations to my entities?

**Comment by mmdance** [comment]
if I understand correctly, the annotation processor generates entities based on classes where there is an "id" annotation.
```java
protected Configuration createConfiguration(RoundEnvironment roundEnv) {
        Class<? extends Annotation> entity = Id.class;
        this.roundEnv = roundEnv;
        CodegenModule codegenModule = new CodegenModule();
        JavaTypeMappings typeMappings = new JavaTypeMappings();
        codegenModule.bind(TypeMappings.class, typeMappings);
        codegenModule.bind(QueryTypeFactory.class, new QueryTypeFactoryImpl("", "", ""));
        SpringDataJdbcConfiguration springDataJdbcConfiguration = new SpringDataJdbcConfiguration(roundEnv, this.processingEnv, entity, (Class)null, (Class)null, (Class)null, SpringDataJdbcAnnotationProcessor.Ignored.class, typeMappings, codegenModule);
        this.conf = springDataJdbcConfiguration;
        return springDataJdbcConfiguration;
    }

    protected TypeElementHandler createElementHandler(TypeMappings typeMappings, QueryTypeFactory queryTypeFactory) {
        return new CustomElementHandler(this.conf, this.typeFactory, typeMappings, queryTypeFactory, this.processingEnv.getElementUtils(), this.roundEnv);
    }

    protected CustomExtendedTypeFactory createTypeFactory(Set<Class<? extends Annotation>> entityAnnotations, TypeMappings typeMappings, QueryTypeFactory queryTypeFactory) {
        CustomExtendedTypeFactory customExtendedTypeFactory = new CustomExtendedTypeFactory(this.processingEnv, entityAnnotations, typeMappings, queryTypeFactory, this.conf.getVariableNameFunction());
        this.typeFactory = customExtendedTypeFactory;
        return customExtendedTypeFactory;
    }

    protected Set<TypeElement> collectElements() {
        return (Set)this.roundEnv.getElementsAnnotatedWith(this.conf.getEntityAnnotation()).stream().map(Element::getEnclosingElement).filter((element) -> {
            return element instanceof TypeElement;
        }).map((element) -> {
            return (TypeElement)element;
        }).collect(Collectors.toSet());
    }

    protected String getClassName(EntityType model) {
        return model.getFullName();
    }

    @Documented
    @Retention(RetentionPolicy.RUNTIME)
    private @interface Ignored {
    }
```

**Comment by lpandzic** [comment]
Yes, it generates Q classes for classes with an Id field.

**Comment by mmdance** [comment]
So, I've just added the dependencies
```xml
<dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>${querydsl.version}</version>
        </dependency>

        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-codegen</artifactId>
            <version>${querydsl.version}</version>
        </dependency>
```
But still the annotation processor does not generate entities. 
It seems like there is no problem with annotation processor registration
![image](https://user-images.githubusercontent.com/44356971/100646649-f4a34480-3346-11eb-9aca-d92ab67bfc2f.png)

**Comment by mmdance** [comment]
> So, I've just added the dependencies
> 
> ```
> <dependency>
>             <groupId>com.querydsl</groupId>
>             <artifactId>querydsl-apt</artifactId>
>             <version>${querydsl.version}</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>com.querydsl</groupId>
>             <artifactId>querydsl-sql-codegen</artifactId>
>             <version>${querydsl.version}</version>
>         </dependency>
> ```
> 
> But still the annotation processor does not generate entities.
> It seems like there is no problem with annotation processor registration
> ![image](https://user-images.githubusercontent.com/44356971/100646649-f4a34480-3346-11eb-9aca-d92ab67bfc2f.png)
> I don't know what's wrong...

**Comment by mmdance** [comment]
Sorry, I accidentally closed the issue.

**Comment by lpandzic** [comment]
Can you share your code on github?

**Comment by lpandzic** [comment]
Also, are you compiling with `-parameters` argument passed to the compiler like it is defined in [README.md](https://github.com/infobip/infobip-spring-data-querydsl#-requirements)?

**Comment by mmdance** [comment]
Oh it's strange, if maven-compiler-plugin is switched off, the annotation processor works...

**Comment by mmdance** [comment]
> Can you share your code on github as a repository?

Sorry I can't. I haven't pushed the project to github yet.

**Comment by mmdance** [comment]
> Also, are you compiling with `-parameters` argument passed to the compiler like it is defined in [README.md](https://github.com/infobip/infobip-spring-data-querydsl#-requirements)?

My maven compiler plugin
```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <parameters>true</parameters>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.16</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.4.1.Final</version>
                        </path>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>2.0.4.RELEASE</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>
                            -Amapstruct.defaultComponentModel=spring
                        </compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
```

**Comment by mmdance** [comment]
aaaaahhhmmmmmm what?
```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <parameters>true</parameters>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.16</version>
                        </path>
                        <path>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.4.1.Final</version>
                        </path>
                        <path>
                            <groupId>org.springframework.boot</groupId>
                            <artifactId>spring-boot-configuration-processor</artifactId>
                            <version>2.0.4.RELEASE</version>
                        </path>
                    </annotationProcessorPaths>
                    <compilerArgs>
                        <compilerArg>
                            -Amapstruct.defaultComponentModel=spring
                        </compilerArg>
                    </compilerArgs>
                </configuration>
            </plugin>
```
when I commented щге all annotation processors, the spring-data-jdbc-annotation-processor started working
but... It still doesn't work
![image](https://user-images.githubusercontent.com/44356971/100659486-5c628b00-3359-11eb-85de-94a4a924b9f0.png)

**Comment by mmdance** [comment]
I think it conflicts with lombok...

**Comment by mmdance** [comment]
![image](https://user-images.githubusercontent.com/44356971/100662524-b1080500-335d-11eb-8a26-4412ea2ddea3.png)
Sooo, I have to solve why the annotation processor doesn't work with lombok.

**Comment by lpandzic** [comment]
It does work with lombok, but I haven't tried to use it with mapstruct.

**Comment by mmdance** [comment]
> It does work with lombok, but I haven't tried to use it with mapstruct.

I've checked. If I switch off lombok, the annotation processor works.
```xml
<plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <parameters>true</parameters>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
<!--                        <path>-->
<!--                            <groupId>org.projectlombok</groupId>-->
<!--                            <artifactId>lombok</artifactId>-->
<!--                            <version>1.18.16</version>-->
<!--                        </path>-->
<!--                        <path>-->
<!--                            <groupId>org.mapstruct</groupId>-->
<!--                            <artifactId>mapstruct-processor</artifactId>-->
<!--                            <version>1.4.1.Final</version>-->
<!--                        </path>-->
<!--                        <path>-->
<!--                            <groupId>org.projectlombok</groupId>-->
<!--                            <artifactId> lombok-mapstruct-binding</artifactId>-->
<!--                            <version>0.1.0</version>-->
<!--                        </path>-->
<!--                        <path>-->
<!--                            <groupId>org.springframework.boot</groupId>-->
<!--                            <artifactId>spring-boot-configuration-processor</artifactId>-->
<!--                            <version>2.4.0</version>-->
<!--                        </path>-->
                    </annotationProcessorPaths>
                    <!--                    <compilerArgs>-->
                    <!--                        <compilerArg>-->
                    <!--                            -Amapstruct.defaultComponentModel=spring-->
                    <!--                        </compilerArg>-->
                    <!--                    </compilerArgs>-->
                </configuration>
            </plugin>
```
![image](https://user-images.githubusercontent.com/44356971/100710672-b6df0400-33b8-11eb-8413-c34df3542480.png)

If lombok works then the annotation processor doesn't generate any entity
```xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <parameters>true</parameters>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.16</version>
                        </path>
<!--                        <path>-->
<!--                            <groupId>org.mapstruct</groupId>-->
<!--                            <artifactId>mapstruct-processor</artifactId>-->
<!--                            <version>1.4.1.Final</version>-->
<!--                        </path>-->
<!--                        <path>-->
<!--                            <groupId>org.projectlombok</groupId>-->
<!--                            <artifactId> lombok-mapstruct-binding</artifactId>-->
<!--                            <version>0.1.0</version>-->
<!--                        </path>-->
<!--                        <path>-->
<!--                            <groupId>org.springframework.boot</groupId>-->
<!--                            <artifactId>spring-boot-configuration-processor</artifactId>-->
<!--                            <version>2.4.0</version>-->
<!--                        </path>-->
                    </annotationProcessorPaths>
                    <!--                    <compilerArgs>-->
                    <!--                        <compilerArg>-->
                    <!--                            -Amapstruct.defaultComponentModel=spring-->
                    <!--                        </compilerArg>-->
                    <!--                    </compilerArgs>-->
                </configuration>
            </plugin>
```
![image](https://user-images.githubusercontent.com/44356971/100710813-fd346300-33b8-11eb-80d6-a71f1d544788.png)

**Comment by mmdance** [comment]
So, the annotation processor obviously conflicts with lombok annotation processor, and I don't know why.

**Comment by lpandzic** [comment]
Something is wrong with you project setup.
This [project](https://github.com/lpandzic/infobip-spring-data-querydsl-issue-10-showcase/blob/master/src/test/java/com/github/lpandzic/Issue10Showcase.java) clearly shows that lombok and `infobip-spring-data-jdbc-querydsl` annotation processor can work together.

**Comment by mmdance** [comment]
I understand what is going on. If I don't specify the `lombock-annotation-processor` in `<annotationProcessorPaths>` then both `spring-data-jdbc-annotation-processor` and `lombok` annotation processor work. But in this case `mapstruct` doesn't work because it needs special declaration with the `lombok` [https://stackoverflow.com/questions/47676369/mapstruct-and-lombok-not-working-together](url). But if I specify `lombock` in the `<annotationProcessorPaths>` the `spring-data-jdbc-annotation-processor` doesn't work.

**Comment by lpandzic** [comment]
Have you tried https://stackoverflow.com/a/47684351/607767 option 2?
```
Option 2:

Add the mapstruct-processor dependency to your dependencies and remove the annotationProcessorPaths. This way the maven compiler will pick up all the annotation processors that are in your dependencies.
```

**Comment by mmdance** [comment]
I have just changed maven to gradle and it has worked.

**Comment by mmdance** [comment]
But now I have a problem when perform request with the Predicate.
```
2020-12-01 15:35:56.096 ERROR 14304 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: null; bad SQL grammar [
from product Product
where Product is not null and Product.Price < ?]; nested exception is java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from product Product
where Product is not null and Product.Price < 1500.0' at line 1] with root cause

java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'from product Product
where Product is not null and Product.Price < 1500.0' at line 1
```

**Comment by githubyong** [comment]
hi, i had occur the same quesion.

the querydsl-maven-plugin generated bean like this.
```
public class QExamInfo extends com.querydsl.sql.RelationalPathBase<ExamInfo> {

    private static final long serialVersionUID = -401254998;

    public static final QExamInfo ExamInfo = new QExamInfo("ExamInfo");

    public final StringPath applyDate = createString("applyDate");
```

but QuerydslExpressionFactory#getRelationalPathBaseFromQueryClass method like this
```
    private RelationalPathBase<?> getRelationalPathBaseFromQueryClass(Class<?> queryClass) {
        String fieldName = CaseFormat.UPPER_CAMEL.to(CaseFormat.LOWER_CAMEL, queryClass.getSimpleName().substring(1));
        Field field = ReflectionUtils.findField(queryClass, fieldName);

        if (field == null) {
            throw new IllegalArgumentException("Did not find a static field of the same type in " + queryClass);
        }

        return (RelationalPathBase<?>) ReflectionUtils.getField(field, null);
    }

```
the later use CaseFormat.LOWER_CAMEL, so can't find field.

**Comment by lpandzic** [comment]
Hi @githubyong , please open a new issue.
